-- =============================================
-- Flori API — 전체 스키마 스냅샷 (SSOT)
-- =============================================
-- 이 파일은 현재 DB의 "전체 현재 상태"를 담는 단일 정본이다.
-- 스키마 관리는 DDL 직접 관리 방식: 이 파일을 RDS/로컬 DB에 수동 적용하고,
-- 이후 변경은 docs/sql/migration/ 의 증분 스크립트로 적용한 뒤 이 파일에도 반영한다.
-- 엔티티-스키마 정합성은 애플리케이션 부팅 시 hibernate ddl-auto=validate 로 강제된다.
--
-- 설계 원칙:
--   * 기본키(PK)는 BIGINT GENERATED BY DEFAULT AS IDENTITY — DB가 시퀀스로 생성.
--   * RLS(행 수준 보안) 미사용 → 멀티테넌시는 애플리케이션이 user_id로 강제.
--   * 외래키(FK) 제약 미사용 → 모든 참조(user_id, sale_id, recurring_id, account_id 등)는
--     컬럼만 유지하는 "간접참조"다. 참조 무결성·연쇄삭제는 애플리케이션이 책임진다.
--   * 자체 users 테이블 — 모든 user_id가 users(id)를 논리적으로 참조(FK 제약 없음).
--   * 인증은 소셜 전용(KAKAO/GOOGLE/NAVER) — 비밀번호 컬럼 없음.
--   * jsonb / 배열 / timestamptz 타입 유지, 복합 unique 제약 유지.
-- =============================================

-- updated_at 자동 갱신 트리거 함수
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =============================================
-- 사용자 (소셜 전용 자체 인증)
-- 소셜 전용이므로 비밀번호 컬럼 없음. email/nickname은 register/complete에서 항상 채워진다(NOT NULL).
-- 가게/사장 프로필은 별도 user_profiles 테이블에 1:1로 저장한다(아래).
-- =============================================
CREATE TABLE users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  email VARCHAR(255) NOT NULL UNIQUE,
  nickname VARCHAR(100) NOT NULL,
  provider VARCHAR(20) NOT NULL,
  provider_id VARCHAR(255),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_admin BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 같은 소셜 신원 = 같은 사용자 (provider_id 있는 행에만 적용)
CREATE UNIQUE INDEX uq_users_provider_identity
  ON users (provider, provider_id)
  WHERE provider_id IS NOT NULL;

-- 닉네임 전역 유일 (정확 일치, case-sensitive). 위반 시 제약명으로 닉네임 충돌을 식별한다.
CREATE UNIQUE INDEX uq_users_nickname ON users (nickname);

CREATE TRIGGER update_users_updated_at
  BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 사용자 프로필 (users와 1:1) — PK이자 FK인 user_id
-- storeName(가게명)은 users.nickname(계정 표시명)과 분리해 저장한다.
-- =============================================
CREATE TABLE user_profiles (
  user_id BIGINT PRIMARY KEY,
  store_name TEXT NOT NULL,
  phone_number TEXT NOT NULL,
  profile_image_url TEXT,
  region_sido TEXT NOT NULL,
  region_sigungu TEXT,
  owner_age_range TEXT,
  interests TEXT[] NOT NULL DEFAULT '{}',
  specialties TEXT[] NOT NULL DEFAULT '{}',
  referral_sources TEXT[] NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER update_user_profiles_updated_at
  BEFORE UPDATE ON user_profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- refresh token 저장소 (회전/세션 추적 + 통계)
-- 보안: 원문 대신 SHA-256 해시만 저장(원문 DB 저장 금지 — HARD).
-- 통계: 발급 컨텍스트(채널/기기/UA/IP) + 회전 계보(parent/세션시작/재발급수) + 종료 사유(status)를 축적해
--       추후 세션/로그인 분석(채널별 사용·기기 분포·세션 lifetime·DAU 등)에 활용한다.
-- =============================================
CREATE TABLE refresh_tokens (
  id                 BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id            BIGINT NOT NULL,
  token_hash         VARCHAR(64) NOT NULL UNIQUE,
  parent_token_id    BIGINT,                          -- 회전 계보: 직전(재발급원) 토큰 id
  client_id          VARCHAR(64),                     -- 채널 식별자(app/web 등). X-Client-Id 헤더
  device_id          VARCHAR(128),                    -- 디바이스 식별자. X-Device-Id 헤더
  user_agent         VARCHAR(512),                    -- 발급 시 User-Agent
  created_ip         VARCHAR(45),                     -- 발급 시 IP(IPv6 포함)
  status             VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
                       CHECK (status IN ('ACTIVE', 'ROTATED', 'LOGGED_OUT', 'EXPIRED')),
  reissued_count     INT NOT NULL DEFAULT 0,          -- 세션 내 재발급(회전) 횟수
  session_started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), -- 세션 최초 시작(회전 시 계승)
  last_used_at       TIMESTAMPTZ,                     -- 마지막 사용(회전/로그아웃) 시각
  expires_at         TIMESTAMPTZ NOT NULL,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens(expires_at);
CREATE INDEX idx_refresh_tokens_user_last_used ON refresh_tokens(user_id, last_used_at);
CREATE INDEX idx_refresh_tokens_client ON refresh_tokens(client_id);

CREATE TRIGGER update_refresh_tokens_updated_at
  BEFORE UPDATE ON refresh_tokens FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 커스텀 고객 등급 (테넌트별)
-- threshold: NULL = 수동 전용(자동승급 대상 아님). 기본 시드: 신규(0)/단골(5)/VIP(10)/블랙리스트(NULL).
-- =============================================
CREATE TABLE customer_grades (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  name VARCHAR(50) NOT NULL,
  threshold INTEGER,                 -- NULL = 수동 전용(자동승급 대상 아님)
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, name)
);

CREATE INDEX idx_customer_grades_user ON customer_grades(user_id);

-- =============================================
-- 고객
-- 구매 통계(횟수/총액/최초·최근 구매일)는 sales에서 실시간 집계(SSOT) — 컬럼 미보유.
-- grade_id: customer_grades(id) 논리참조(FK 제약 없음). grade_locked=true이면 자동승급 제외.
-- =============================================
CREATE TABLE customers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  name VARCHAR(100) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  grade_id BIGINT,
  grade_locked BOOLEAN NOT NULL DEFAULT false,
  gender VARCHAR(10) DEFAULT NULL CHECK (gender IN ('male', 'female')),
  memo TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (phone, user_id)
);

CREATE INDEX idx_customers_phone ON customers(phone);
CREATE INDEX idx_customers_grade_id ON customers(grade_id);
CREATE INDEX idx_customers_user_id ON customers(user_id);

CREATE TRIGGER update_customers_updated_at
  BEFORE UPDATE ON customers FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 고정비(반복 지출) 템플릿 — expenses.recurring_id가 참조하므로 먼저 생성
-- =============================================
CREATE TABLE recurring_expenses (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  item_name TEXT NOT NULL,
  category_id BIGINT,
  unit_price INTEGER NOT NULL CHECK (unit_price >= 0),
  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
  payment_method_id BIGINT,
  vendor TEXT,
  memo TEXT,
  frequency VARCHAR(10) NOT NULL CHECK (frequency IN ('weekly', 'monthly', 'yearly')),
  interval_count INTEGER NOT NULL DEFAULT 1 CHECK (interval_count > 0),
  days_of_week INTEGER[] NOT NULL DEFAULT '{}',   -- weekly: 0(일)~6(토)
  days_of_month INTEGER[] NOT NULL DEFAULT '{}',  -- monthly: 1~31
  yearly_dates JSONB NOT NULL DEFAULT '[]'::jsonb, -- yearly: [{"m":n,"d":n}]
  start_date DATE NOT NULL,
  end_date DATE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_recurring_expenses_user ON recurring_expenses(user_id);
CREATE INDEX idx_recurring_expenses_active ON recurring_expenses(is_active) WHERE is_active = TRUE;

CREATE TRIGGER update_recurring_expenses_updated_at
  BEFORE UPDATE ON recurring_expenses FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 예약 (sale_id는 sales를 논리 참조 — FK 제약 없음)
-- =============================================
CREATE TABLE reservations (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  date DATE NOT NULL,
  time TIME,
  customer_name TEXT NOT NULL DEFAULT '',
  customer_phone TEXT,
  title TEXT NOT NULL DEFAULT '',
  memo TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'completed', 'cancelled')),
  sale_id BIGINT,
  amount INTEGER DEFAULT 0,
  reminder_at TIMESTAMPTZ,
  reminder_sent BOOLEAN NOT NULL DEFAULT FALSE,
  pickup_completed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_reservations_date ON reservations(date);
CREATE INDEX idx_reservations_status ON reservations(status);
CREATE INDEX idx_reservations_user_id ON reservations(user_id);

CREATE TRIGGER update_reservations_updated_at
  BEFORE UPDATE ON reservations FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 매출
-- =============================================
CREATE TABLE sales (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  date DATE NOT NULL,
  category_id BIGINT,
  amount INTEGER NOT NULL,
  payment_method_id BIGINT,
  channel_id BIGINT,
  customer_name VARCHAR(100),
  customer_phone VARCHAR(20),
  customer_id BIGINT,
  memo TEXT,
  is_unpaid BOOLEAN NOT NULL DEFAULT FALSE,
  has_review BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_sales_date ON sales(date);
CREATE INDEX idx_sales_customer_id ON sales(customer_id);
CREATE INDEX idx_sales_payment_method_id ON sales(payment_method_id);
CREATE INDEX idx_sales_category_id ON sales(category_id);
CREATE INDEX idx_sales_channel_id ON sales(channel_id);
CREATE INDEX idx_sales_user_id ON sales(user_id);

CREATE TRIGGER update_sales_updated_at
  BEFORE UPDATE ON sales FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 지출 (category CHECK 없음 — 커스텀 카테고리 허용)
-- =============================================
CREATE TABLE expenses (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  date DATE NOT NULL,
  item_name VARCHAR(200) NOT NULL,
  category_id BIGINT,
  unit_price INTEGER NOT NULL,
  quantity INTEGER DEFAULT 1,
  total_amount INTEGER NOT NULL,
  payment_method_id BIGINT,
  card_company VARCHAR(50),
  vendor VARCHAR(100),
  memo TEXT,
  recurring_id BIGINT,
  is_recurring_modified BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  -- 같은 템플릿·같은 날짜 중복 자동생성 방지(NULL recurring_id는 distinct 취급)
  CONSTRAINT expenses_recurring_date_unique UNIQUE (recurring_id, date)
);

CREATE INDEX idx_expenses_date ON expenses(date);
CREATE INDEX idx_expenses_category_id ON expenses(category_id);
CREATE INDEX idx_expenses_user_id ON expenses(user_id);

CREATE TRIGGER update_expenses_updated_at
  BEFORE UPDATE ON expenses FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 고정비 skip ("이것만 삭제" 시 자동생성 재발 방지)
-- =============================================
CREATE TABLE recurring_skips (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  recurring_id BIGINT NOT NULL,
  skip_date DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (recurring_id, skip_date)
);

CREATE INDEX idx_recurring_skips_user ON recurring_skips(user_id);

-- =============================================
-- 라벨 설정 (매출/지출 카테고리·결제방식·채널 통합)
--   domain: 'sale' | 'expense'
--   kind:   'category' | 'payment' | 'channel'  (channel은 sale 전용)
--   value=영문 저장값, label=한글 표시값
-- =============================================
CREATE TABLE label_settings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  domain VARCHAR(20) NOT NULL,
  kind VARCHAR(20) NOT NULL,
  value VARCHAR(100) NOT NULL,
  label VARCHAR(100) NOT NULL,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, domain, kind, value)
);

CREATE INDEX idx_label_settings_user_domain_kind ON label_settings(user_id, domain, kind);

-- =============================================
-- 사진 태그
-- =============================================
CREATE TABLE photo_tags (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  name VARCHAR(50) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (name, user_id)
);

CREATE INDEX idx_photo_tags_user_id ON photo_tags(user_id);

-- =============================================
-- 사진 카드 (photos: [{url, originalName}] jsonb)
-- =============================================
CREATE TABLE photo_cards (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  memo TEXT,
  tags TEXT[] DEFAULT '{}',
  photos JSONB DEFAULT '[]',
  sale_id BIGINT,
  customer_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_photo_cards_tags ON photo_cards USING GIN(tags);
CREATE INDEX idx_photo_cards_sale_id ON photo_cards(sale_id);
CREATE INDEX idx_photo_cards_created_at ON photo_cards(created_at DESC);
CREATE INDEX idx_photo_cards_user_id ON photo_cards(user_id);
CREATE INDEX idx_photo_cards_user_customer ON photo_cards(user_id, customer_id);

CREATE TRIGGER update_photo_cards_updated_at
  BEFORE UPDATE ON photo_cards FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 푸시 구독 (FCM 토큰도 endpoint에 저장)
-- =============================================
CREATE TABLE push_subscriptions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  endpoint TEXT NOT NULL UNIQUE,
  p256dh TEXT,
  auth TEXT,
  user_agent TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_push_subscriptions_user_id ON push_subscriptions(user_id);

CREATE TRIGGER update_push_subscriptions_updated_at
  BEFORE UPDATE ON push_subscriptions FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 일정 (다중일)
-- =============================================
CREATE TABLE schedules (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  title TEXT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  color VARCHAR(7) NOT NULL DEFAULT '#f43f5e',
  memo TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_schedules_user_id ON schedules(user_id);
CREATE INDEX idx_schedules_range ON schedules(start_date, end_date);

CREATE TRIGGER update_schedules_updated_at
  BEFORE UPDATE ON schedules FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 유저 설정 — key-value 스토어. (user_id, key) 복합 PK, value는 jsonb 원본.
-- 예: ('...', 'bottom_nav', '["dashboard","sales",...]'). 새 설정은 key만 추가.
-- =============================================
CREATE TABLE user_preferences (
  user_id BIGINT NOT NULL,
  key VARCHAR(40) NOT NULL,
  value JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, key)
);

CREATE TRIGGER update_user_preferences_updated_at
  BEFORE UPDATE ON user_preferences FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 알림 발송 멱등성 로그.
-- 같은 (user_id, notification_type, dedup_key) 알림을 중복 발송하지 않도록 원자적으로 기록한다.
-- 스케줄러 재기동·중복 트리거 시 INSERT ... ON CONFLICT DO NOTHING 으로 1회 발송 보장(at-most-once).
-- =============================================
CREATE TABLE notification_log (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  notification_type VARCHAR(40) NOT NULL,
  dedup_key VARCHAR(64) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, notification_type, dedup_key)
);

-- =============================================
-- 커뮤니티 게시판 (단일 커뮤니티 — 테넌트 간 공유)
-- 신원/권한은 author_user_id + 뷰어(JWT)로 계산(애플리케이션). content는 Tiptap JSON(jsonb).
-- like_count/comment_count는 비정규화. 삭제는 soft delete(deleted_at).
-- =============================================
CREATE TABLE community_posts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  author_user_id BIGINT NOT NULL,
  category VARCHAR(20) NOT NULL CHECK (category IN ('notice', 'daily', 'question', 'knowledge', 'review', 'etc')),
  title VARCHAR(255) NOT NULL,
  content JSONB NOT NULL DEFAULT '{}'::jsonb,
  content_text TEXT NOT NULL DEFAULT '',
  image_urls TEXT[] NOT NULL DEFAULT '{}',
  is_secret BOOLEAN NOT NULL DEFAULT FALSE,
  is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
  like_count INTEGER NOT NULL DEFAULT 0,
  comment_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);

-- 목록: 미삭제만 + 고정글 우선 + 최신순.
CREATE INDEX idx_community_posts_feed ON community_posts(is_pinned DESC, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_community_posts_category ON community_posts(category);
CREATE INDEX idx_community_posts_author ON community_posts(author_user_id);

CREATE TRIGGER update_community_posts_updated_at
  BEFORE UPDATE ON community_posts FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TABLE community_comments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  post_id BIGINT NOT NULL,
  parent_id BIGINT,
  author_user_id BIGINT NOT NULL,
  content TEXT NOT NULL,
  is_secret BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);

CREATE INDEX idx_community_comments_post ON community_comments(post_id);
CREATE INDEX idx_community_comments_parent ON community_comments(parent_id);

CREATE TABLE community_likes (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  post_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (post_id, user_id)
);

CREATE INDEX idx_community_likes_post ON community_likes(post_id);

-- ── 사업자 인증 ────────────────────────────────────────────────────────────
-- 커뮤니티 접근 게이팅용. 사용자가 사업자등록증을 제출하면 PENDING으로 기록되고,
-- 운영자가 수동 검토 후 status를 APPROVED/REJECTED로 갱신한다(현재 관리자 API 없음).
-- 인증됨 = 해당 user_id에 status='APPROVED' 행 존재. 재신청은 새 행으로 누적.
CREATE TABLE business_verifications (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  business_number VARCHAR(10) NOT NULL,
  business_name VARCHAR(255) NOT NULL,
  representative_name VARCHAR(100) NOT NULL,
  business_license_url TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
    CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
  reject_reason TEXT,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_business_verifications_user ON business_verifications(user_id);
-- user당 PENDING 1건만 허용(중복 신청 방지).
CREATE UNIQUE INDEX uq_business_verifications_pending
  ON business_verifications(user_id) WHERE status = 'PENDING';

CREATE TRIGGER update_business_verifications_updated_at
  BEFORE UPDATE ON business_verifications FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ── AI 게이트웨이 로깅 ──────────────────────────────────────────────────────
-- Spring 게이트웨이가 web↔ai-server 사이 모든 AI 호출을 기록한다. ai-server는 stateless.
-- FK 미사용(간접참조). 토큰 사용량은 각 이벤트 테이블에 직접 기록(별도 usage 테이블 없음).
CREATE TABLE ai_chat_session (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  session_token VARCHAR(64) NOT NULL UNIQUE,
  feature VARCHAR(20) NOT NULL CHECK (feature IN ('chat', 'proactive', 'ocr')),
  title VARCHAR(255),
  first_message_at TIMESTAMPTZ,
  last_message_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_ai_chat_session_user ON ai_chat_session(user_id, last_message_at DESC) WHERE deleted_at IS NULL;
CREATE TRIGGER update_ai_chat_session_updated_at
  BEFORE UPDATE ON ai_chat_session FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TABLE ai_chat_message (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  session_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  role VARCHAR(16) NOT NULL CHECK (role IN ('user', 'assistant')),
  content TEXT NOT NULL DEFAULT '',
  content_json JSONB,
  model VARCHAR(64),
  input_tokens INTEGER,
  output_tokens INTEGER,
  latency_ms INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_ai_chat_message_session ON ai_chat_message(session_id, created_at);
CREATE INDEX idx_ai_chat_message_usage ON ai_chat_message(user_id, created_at);

CREATE TABLE ai_write_proposal (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  proposal_id VARCHAR(64) NOT NULL UNIQUE,
  user_id BIGINT NOT NULL,
  action VARCHAR(40) NOT NULL CHECK (action IN ('create_reservation')),
  payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  source VARCHAR(20) NOT NULL DEFAULT 'ocr_image',
  status VARCHAR(16) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'expired', 'rejected')),
  result_id BIGINT,
  model VARCHAR(64),
  input_tokens INTEGER,
  output_tokens INTEGER,
  latency_ms INTEGER,
  expires_at TIMESTAMPTZ,
  confirmed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_ai_write_proposal_user ON ai_write_proposal(user_id, status);
CREATE TRIGGER update_ai_write_proposal_updated_at
  BEFORE UPDATE ON ai_write_proposal FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TABLE ai_proactive_log (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  suggestions_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  suggestion_count INTEGER NOT NULL DEFAULT 0,
  model VARCHAR(64),
  input_tokens INTEGER,
  output_tokens INTEGER,
  latency_ms INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_ai_proactive_log_user ON ai_proactive_log(user_id, created_at);

-- =============================================
-- 사전등록(waitlist)
-- 출시 전 선착순 100명 모집. 공개 폼(이메일 + 가게명, 둘 다 필수), 로그인 불필요.
-- 이메일은 정규화(trim+소문자)하여 UNIQUE로 중복 등록 방지. 인증/테넌시와 무관한 독립 테이블.
-- =============================================
CREATE TABLE waitlist_registrations (
  id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  email       VARCHAR(254) NOT NULL UNIQUE,
  shop_name   VARCHAR(50)  NOT NULL,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- =============================================
-- 유저 인터뷰 모집(interview)
-- 출시 전 인터뷰 참여자 모집. 공개 폼(이름 + 전화번호, 둘 다 필수), 로그인 불필요.
-- 전화번호는 정규화(숫자만)하여 UNIQUE로 중복 신청 방지. 인증/테넌시와 무관한 독립 테이블.
-- =============================================
CREATE TABLE interview_requests (
  id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name        VARCHAR(50)  NOT NULL,
  phone       VARCHAR(20)  NOT NULL UNIQUE,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
