-- 유저 인터뷰 모집(interview) — 출시 전 인터뷰 참여자 모집. 공개 폼(이름 + 전화번호), 로그인 불필요.
-- 전화번호는 정규화(숫자만)하여 UNIQUE로 중복 신청 방지. 인증/테넌시와 무관한 독립 테이블.
START TRANSACTION;

CREATE TABLE interview_requests (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL,
    phone       VARCHAR(20)  NOT NULL UNIQUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMIT;
