-- flori AI 게이트웨이 로깅 테이블 — 대화 세션/메시지, OCR 쓰기제안, proactive 제안 로그.
-- Spring server(게이트웨이)가 web↔ai-server 사이에서 모든 AI 호출을 여기에 기록한다.
-- ai-server(FastAPI)는 stateless — 세션/영속은 전부 게이트웨이 소유.
-- FK 제약 미사용(간접참조) — 참조 무결성/연쇄정리는 애플리케이션 책임. all-tables-ddl.sql과 동일.
-- 토큰 사용량은 별도 usage 테이블 없이 각 이벤트 테이블(메시지/제안/proactive)에 직접 기록한다.
START TRANSACTION;

-- 1) 대화 세션 — web이 session_token으로 멀티턴을 이어간다(ai-server의 session_id 대체).
CREATE TABLE ai_chat_session (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  session_token VARCHAR(64) NOT NULL UNIQUE,
  feature VARCHAR(20) NOT NULL CHECK (feature IN ('chat', 'proactive', 'ocr')),
  title VARCHAR(255),
  first_message_at TIMESTAMPTZ,
  last_message_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_ai_chat_session_user ON ai_chat_session(user_id, last_message_at DESC) WHERE deleted_at IS NULL;
CREATE TRIGGER update_ai_chat_session_updated_at
  BEFORE UPDATE ON ai_chat_session FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- 2) 대화 메시지(턴) — 토큰/모델/지연을 이 행에 직접 기록(별도 usage 테이블 없음).
CREATE TABLE ai_chat_message (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  session_id BIGINT NOT NULL,                 -- 간접참조 ai_chat_session.id (FK 없음)
  user_id BIGINT NOT NULL,
  role VARCHAR(16) NOT NULL CHECK (role IN ('user', 'assistant')),
  content TEXT NOT NULL DEFAULT '',
  content_json JSONB,                         -- 구조화 응답(차트/카드 등) 향후 확장용
  model VARCHAR(64),
  input_tokens INTEGER,
  output_tokens INTEGER,
  latency_ms INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_ai_chat_message_session ON ai_chat_message(session_id, created_at);
CREATE INDEX idx_ai_chat_message_usage ON ai_chat_message(user_id, created_at);  -- 일일 사용량 캡 집계

-- 3) OCR→예약 쓰기 제안(human-in-loop). ai-server Redis pending을 게이트웨이 DB로 승격 — 감사/만료/멱등.
CREATE TABLE ai_write_proposal (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  proposal_id VARCHAR(64) NOT NULL UNIQUE,
  user_id BIGINT NOT NULL,
  action VARCHAR(40) NOT NULL CHECK (action IN ('create_reservation')),
  payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  source VARCHAR(20) NOT NULL DEFAULT 'ocr_image',
  status VARCHAR(16) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'expired', 'rejected')),
  result_id BIGINT,                           -- 간접참조 reservations.id (확인 생성 시)
  model VARCHAR(64),                          -- OCR vision 사용량
  input_tokens INTEGER,
  output_tokens INTEGER,
  latency_ms INTEGER,
  expires_at TIMESTAMPTZ,
  confirmed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_ai_write_proposal_user ON ai_write_proposal(user_id, status);
CREATE TRIGGER update_ai_write_proposal_updated_at
  BEFORE UPDATE ON ai_write_proposal FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- 4) proactive 제안 노출 로그 — 생성/노출된 제안 + 토큰(분석·사용량용).
CREATE TABLE ai_proactive_log (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  suggestions_json JSONB NOT NULL DEFAULT '[]'::jsonb,   -- [{title, detail}, ...]
  suggestion_count INTEGER NOT NULL DEFAULT 0,
  model VARCHAR(64),
  input_tokens INTEGER,
  output_tokens INTEGER,
  latency_ms INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_ai_proactive_log_user ON ai_proactive_log(user_id, created_at);

COMMIT;
