-- 정보 피드(인사이트) 부활 + 신규 — 경매 시세·지원사업·트렌드/뉴스·스크랩.
-- 부활: trend_articles, insight_scraps (2026-06-06 드롭됨).
-- 신규: flower_auction_prices, support_programs.
-- 인스타그램(팔로우) 테이블은 부활하지 않는다(기능 제거).
-- 설계: FK 없음(간접참조), 공유 읽기 테이블 3 + 개인(user_id) 1(insight_scraps).
--
-- 경매 시세는 단일 시장(aT 양재)만 제공한다 — 실제 aT 화훼유통정보 f001 API는 시장/법인 구분이
-- 없는 단일 시장 응답이다(라이브 테스트로 확인). 따라서 flower_markets(다중 시장 매핑)는 두지 않고,
-- 응답 텍스트(절화/관엽/난/춘란 등)를 그대로 적재한다.

START TRANSACTION;

-- 1) 트렌드·뉴스 기사 (공유 큐레이션) — 부활
CREATE TABLE trend_articles (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category TEXT NOT NULL CHECK (category IN ('flower', 'inspiration', 'business', 'industry')),
  title TEXT NOT NULL,
  summary TEXT NOT NULL,
  key_points JSONB NOT NULL DEFAULT '[]'::jsonb,
  source_url TEXT NOT NULL,
  source_name TEXT,
  published_at TIMESTAMPTZ,
  collected_at DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_trend_articles_category ON trend_articles(category);
CREATE INDEX idx_trend_articles_collected_at ON trend_articles(collected_at DESC);
CREATE UNIQUE INDEX idx_trend_articles_source_url ON trend_articles(source_url);

-- 2) 경매 시세 — 일별 경락가 (aT f001 적재, 단일 시장 = 양재) — 신규
--    응답 필드(snake_case) 그대로 적재: sale_date/flower_gubn/pum_name/good_name/lv_nm + 금액/수량.
--    등락률 컬럼 없음: 평균단가 시계열로 조회 시 파생 계산(idx_fap_item_date).
--    key 컬럼(품종/등급)은 NULL 회피 위해 NOT NULL DEFAULT '' (UNIQUE 신뢰성).
CREATE TABLE flower_auction_prices (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  sale_date DATE NOT NULL,
  flower_gubn TEXT NOT NULL,                  -- 절화/관엽/난/춘란 (f001 응답 텍스트)
  pum_name TEXT NOT NULL,                     -- 품목
  good_name TEXT NOT NULL DEFAULT '',         -- 품종
  lv_nm TEXT NOT NULL DEFAULT '',             -- 등급 (특2/상1/보3 …)
  avg_amt INTEGER,
  max_amt INTEGER,
  min_amt INTEGER,
  tot_qty BIGINT,
  tot_amt BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (sale_date, flower_gubn, pum_name, good_name, lv_nm)
);
CREATE INDEX idx_fap_item_date ON flower_auction_prices(flower_gubn, pum_name, good_name, lv_nm, sale_date DESC);
CREATE INDEX idx_fap_date ON flower_auction_prices(sale_date DESC);

-- 3) 지원사업 (소진공·기업마당·K-Startup 큐레이션) — 신규
CREATE TABLE support_programs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  source TEXT NOT NULL,
  source_id TEXT NOT NULL,
  title TEXT NOT NULL,
  agency TEXT,
  category TEXT CHECK (category IN ('fund', 'marketing', 'education')),
  target TEXT,
  summary TEXT,
  apply_start DATE,
  apply_end DATE,
  source_url TEXT,
  collected_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (source, source_id)
);
CREATE INDEX idx_support_programs_end ON support_programs(apply_end);
CREATE INDEX idx_support_programs_category ON support_programs(category);

-- 4) 인사이트 스크랩 (사장님별 개인 북마크) — 부활
--    target_type: 'trend'(trend_articles) | 'grant'(support_programs). target_id 는 FK 없는 간접참조.
CREATE TABLE insight_scraps (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  target_type TEXT NOT NULL CHECK (target_type IN ('trend', 'grant')),
  target_id BIGINT NOT NULL,
  memo TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, target_type, target_id)
);
CREATE INDEX idx_insight_scraps_user ON insight_scraps(user_id);
CREATE INDEX idx_insight_scraps_target ON insight_scraps(target_type, target_id);
CREATE INDEX idx_insight_scraps_user_type_created
  ON insight_scraps(user_id, target_type, created_at DESC);
CREATE TRIGGER update_insight_scraps_updated_at
  BEFORE UPDATE ON insight_scraps FOR EACH ROW EXECUTE FUNCTION update_updated_at();

COMMIT;
