-- flori AI 마케팅(블로그 초안) 게이트웨이 테이블 — 말투 프로필 + 생성 콘텐츠 영속.
-- Spring server(게이트웨이)가 web↔ai-server 사이에서 블로그 초안 생성을 중개·로깅한다.
-- ai-server(FastAPI)는 stateless — tone_profile/store_context 조립과 영속은 전부 게이트웨이 소유.
-- FK 제약 미사용(간접참조) — 참조 무결성/연쇄정리는 애플리케이션 책임. all-tables-ddl.sql과 동일.
-- 토큰 사용량은 별도 usage 테이블 없이 콘텐츠 행에 직접 기록한다(메시지/제안과 동일 컨벤션).
START TRANSACTION;

-- 1) 말투 프로필 — 유저당 1행(upsert). 사장 블로그 샘플 1~3개를 매 생성 시 few-shot으로 주입.
CREATE TABLE ai_tone_profile (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL UNIQUE,                       -- 간접참조 users.id (FK 없음), 유저당 1행
  samples_json JSONB NOT NULL DEFAULT '[]'::jsonb,      -- ["샘플1", "샘플2", ...] 최대 3
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER update_ai_tone_profile_updated_at
  BEFORE UPDATE ON ai_tone_profile FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- 2) 마케팅 생성 콘텐츠 — 입력(키워드/상황/메모/사진·조립한 맥락)과 출력(BlogDraft)을 함께 보관.
--    목록/상세/복사/재생성/소프트삭제를 web이 제공한다. 토큰/모델/지연을 이 행에 직접 기록.
CREATE TABLE ai_marketing_content (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  channel VARCHAR(20) NOT NULL DEFAULT 'blog' CHECK (channel IN ('blog')),
  input_json JSONB NOT NULL DEFAULT '{}'::jsonb,        -- {keyword, situation, memo, photoUrls, storeContext}
  output_json JSONB NOT NULL DEFAULT '{}'::jsonb,       -- BlogDraft {title, sections, faq, hashtags}
  model VARCHAR(64),
  input_tokens INTEGER,
  output_tokens INTEGER,
  latency_ms INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);
CREATE INDEX idx_ai_marketing_content_user
  ON ai_marketing_content(user_id, channel, created_at DESC) WHERE deleted_at IS NULL;

COMMIT;
