-- 매출/지출 라벨 설정 4테이블(sale_categories, payment_methods, expense_categories,
-- expense_payment_methods)을 단일 label_settings로 통합 + color 컬럼 제거 + 매출 채널 편입.
-- 실행 전 백업 권장.

BEGIN;

-- 1. 통합 테이블 생성
CREATE TABLE label_settings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  domain VARCHAR(20) NOT NULL,
  kind VARCHAR(20) NOT NULL,
  value VARCHAR(100) NOT NULL,
  label VARCHAR(100) NOT NULL,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, domain, kind, value)
);

CREATE INDEX idx_label_settings_user_domain_kind ON label_settings(user_id, domain, kind);

-- 2. 기존 4테이블 데이터 이관 (color 제거)
INSERT INTO label_settings (user_id, domain, kind, value, label, sort_order, created_at)
SELECT user_id, 'sale', 'category', value, label, sort_order, created_at FROM sale_categories;

INSERT INTO label_settings (user_id, domain, kind, value, label, sort_order, created_at)
SELECT user_id, 'sale', 'payment', value, label, sort_order, created_at FROM payment_methods;

INSERT INTO label_settings (user_id, domain, kind, value, label, sort_order, created_at)
SELECT user_id, 'expense', 'category', value, label, sort_order, created_at FROM expense_categories;

INSERT INTO label_settings (user_id, domain, kind, value, label, sort_order, created_at)
SELECT user_id, 'expense', 'payment', value, label, sort_order, created_at FROM expense_payment_methods;

-- 3. 매출 채널 기본값 시드(기존 사용자 전원) — 이전엔 sales.reservation_channel enum뿐이라 설정 행이 없었음
INSERT INTO label_settings (user_id, domain, kind, value, label, sort_order)
SELECT u.id, 'sale', 'channel', c.value, c.label, c.sort_order
FROM users u
CROSS JOIN (VALUES
  ('phone', '전화', 1),
  ('kakaotalk', '카카오톡', 2),
  ('naver_booking', '네이버예약', 3),
  ('road', '로드', 4),
  ('other', '기타', 5)
) AS c(value, label, sort_order)
ON CONFLICT (user_id, domain, kind, value) DO NOTHING;

-- 4. 기존 테이블 제거
DROP TABLE sale_categories;
DROP TABLE payment_methods;
DROP TABLE expense_categories;
DROP TABLE expense_payment_methods;

COMMIT;
