-- 토스페이먼츠 자동결제(빌링) + 구독 + 쿠폰.
-- 컨벤션: BIGINT IDENTITY PK, snake_case, FK 미사용(간접참조), updated_at 트리거(update_updated_at()).
-- billing_key.billing_key 는 앱레벨 AES 암호문(평문 금지). identity_hash 는 SHA-256.
START TRANSACTION;

-- 1) billing_key: 유저당 카드 1장(토스 빌링키 보관함)
CREATE TABLE billing_key (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  customer_key VARCHAR(64) NOT NULL,             -- 우리가 생성한 토스 customerKey(UUID)
  billing_key TEXT NOT NULL,                     -- AES 암호문(base64)
  card_company VARCHAR(40),
  card_number_masked VARCHAR(40),
  card_type VARCHAR(20),
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','DELETED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX uq_billing_key_user ON billing_key(user_id);

-- 2) subscription: 유저당 구독 1건
CREATE TABLE subscription (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  plan VARCHAR(10) NOT NULL CHECK (plan IN ('MONTHLY','YEARLY')),
  status VARCHAR(12) NOT NULL CHECK (status IN ('TRIALING','ACTIVE','IN_GRACE','EXPIRED')),
  billing_key_id BIGINT,
  amount INTEGER NOT NULL,
  current_period_start TIMESTAMPTZ,
  current_period_end TIMESTAMPTZ,
  next_billing_at TIMESTAMPTZ NOT NULL,
  cancel_at_period_end BOOLEAN NOT NULL DEFAULT FALSE,
  grace_until TIMESTAMPTZ,
  retry_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX uq_subscription_user ON subscription(user_id);
CREATE INDEX idx_subscription_due ON subscription(next_billing_at)
  WHERE status IN ('TRIALING','ACTIVE','IN_GRACE');

-- 3) payment_history: 결제 시도 장부(append-only)
CREATE TABLE payment_history (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  subscription_id BIGINT NOT NULL,
  order_id VARCHAR(64) NOT NULL,                 -- 우리 생성, 시도마다 유니크
  billing_cycle DATE NOT NULL,                   -- 이 결제가 속한 주기(이용기간 시작일)
  amount INTEGER NOT NULL,
  status VARCHAR(10) NOT NULL CHECK (status IN ('PAID','FAILED','CANCELED')),
  toss_payment_key VARCHAR(64),
  failure_code VARCHAR(60),
  failure_message TEXT,
  approved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX uq_payment_order ON payment_history(order_id);
-- 한 주기당 성공결제 1건만(이중청구 방지)
CREATE UNIQUE INDEX uq_payment_paid_per_cycle ON payment_history(subscription_id, billing_cycle)
  WHERE status = 'PAID';
CREATE INDEX idx_payment_subscription ON payment_history(subscription_id, created_at DESC);

-- 4) coupon: 쿠폰 정의(콘솔 발행)
CREATE TABLE coupon (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  code VARCHAR(40) NOT NULL,
  grant_type VARCHAR(20) NOT NULL DEFAULT 'FREE_DAYS' CHECK (grant_type IN ('FREE_DAYS')),
  days INTEGER NOT NULL,
  valid_from TIMESTAMPTZ,
  valid_until TIMESTAMPTZ,
  max_redemptions INTEGER,
  per_user_limit INTEGER NOT NULL DEFAULT 1,
  redeemed_count INTEGER NOT NULL DEFAULT 0,
  status VARCHAR(12) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','DISABLED')),
  source VARCHAR(20) NOT NULL DEFAULT 'PROMO' CHECK (source IN ('PROMO','REFERRAL','EVENT','MANUAL')),
  memo TEXT,
  created_by BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX uq_coupon_code ON coupon(code);

-- 5) coupon_redemption: 쿠폰 사용 기록
CREATE TABLE coupon_redemption (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  coupon_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  granted_days INTEGER NOT NULL,
  subscription_id BIGINT,                        -- 가입 전 redeem이면 NULL(pending)
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX uq_coupon_redemption_user ON coupon_redemption(coupon_id, user_id);
CREATE INDEX idx_coupon_redemption_coupon ON coupon_redemption(coupon_id, created_at DESC);

-- 6) subscription_eligibility: 어뷰징 방어 신원 원장(탈퇴해도 유지)
CREATE TABLE subscription_eligibility (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  identity_hash VARCHAR(64) NOT NULL,            -- SHA-256("biz:"+businessNumber) (사업자등록번호 기준)
  trial_used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX uq_eligibility_identity ON subscription_eligibility(identity_hash);

-- updated_at 자동 갱신 트리거(기존 공용 함수 update_updated_at() 재사용)
CREATE TRIGGER trg_billing_key_updated BEFORE UPDATE ON billing_key
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_subscription_updated BEFORE UPDATE ON subscription
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_coupon_updated BEFORE UPDATE ON coupon
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_eligibility_updated BEFORE UPDATE ON subscription_eligibility
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

COMMIT;
