-- 커뮤니티 사업자 인증: business_verifications 테이블 신설.
START TRANSACTION;

CREATE TABLE business_verifications (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  business_number VARCHAR(10) NOT NULL,
  business_name VARCHAR(255) NOT NULL,
  representative_name VARCHAR(100) NOT NULL,
  business_license_url TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
    CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
  reject_reason TEXT,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_business_verifications_user ON business_verifications(user_id);
CREATE UNIQUE INDEX uq_business_verifications_pending
  ON business_verifications(user_id) WHERE status = 'PENDING';

CREATE TRIGGER update_business_verifications_updated_at
  BEFORE UPDATE ON business_verifications FOR EACH ROW EXECUTE FUNCTION update_updated_at();

COMMIT;
