-- 커스텀 등급 테이블 + customers.grade_id/grade_locked. 기존 grade(VARCHAR) 제거.
-- 기본 임계값 신규0/단골5/VIP10, 블랙리스트는 수동전용(threshold NULL).
BEGIN;

-- 1. 등급 정의 테이블
CREATE TABLE customer_grades (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  name VARCHAR(50) NOT NULL,
  threshold INTEGER,                 -- NULL = 수동 전용(자동승급 대상 아님)
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, name)
);
CREATE INDEX idx_customer_grades_user ON customer_grades(user_id);

-- 2. 기존 테넌트별 기본 등급 시드
INSERT INTO customer_grades (user_id, name, threshold, sort_order)
SELECT u.id, g.name, g.threshold, g.sort_order
FROM users u
CROSS JOIN (VALUES
  ('신규', 0, 1),
  ('단골', 5, 2),
  ('VIP', 10, 3),
  ('블랙리스트', NULL::int, 4)
) AS g(name, threshold, sort_order)
ON CONFLICT (user_id, name) DO NOTHING;

-- 3. customers 컬럼 추가
ALTER TABLE customers ADD COLUMN IF NOT EXISTS grade_id BIGINT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS grade_locked BOOLEAN NOT NULL DEFAULT false;
CREATE INDEX IF NOT EXISTS idx_customers_grade_id ON customers(grade_id);
-- 구 grade 인덱스(idx_customers_grade)는 6번 DROP COLUMN 시 자동 제거됨

-- 4. grade_id 백필 (기존 grade 문자열 → 시드 등급 매핑)
UPDATE customers c SET grade_id = cg.id
FROM customer_grades cg
WHERE cg.user_id = c.user_id
  AND cg.name = CASE c.grade
    WHEN 'new' THEN '신규'
    WHEN 'regular' THEN '단골'
    WHEN 'vip' THEN 'VIP'
    WHEN 'blacklist' THEN '블랙리스트'
    ELSE '신규'
  END;

-- 5. grade_locked: 블랙리스트였던 고객만 잠금(나머지는 자동 재계산)
UPDATE customers SET grade_locked = true WHERE grade = 'blacklist';

-- 6. 구 grade 컬럼 제거
ALTER TABLE customers DROP COLUMN grade;

COMMIT;
