-- 이미지 인당 스토리지 쿼터: 갤러리(photo-cards) 사용량 카운터 + 증설 요청 이력.
-- 사용량은 presign 시 검사·카드 저장 시 증감, @Scheduled 정합으로 보정. 기본 3GiB(3221225472).
START TRANSACTION;

CREATE TABLE user_storage (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  used_bytes BIGINT NOT NULL DEFAULT 0,
  quota_bytes BIGINT NOT NULL DEFAULT 3221225472,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id)
);

CREATE TABLE storage_increase_requests (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  reason TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  resolved_bytes BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_storage_increase_requests_status ON storage_increase_requests(status, created_at DESC);
CREATE INDEX idx_storage_increase_requests_user ON storage_increase_requests(user_id);

CREATE TRIGGER update_user_storage_updated_at
  BEFORE UPDATE ON user_storage FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_storage_increase_requests_updated_at
  BEFORE UPDATE ON storage_increase_requests FOR EACH ROW EXECUTE FUNCTION update_updated_at();

COMMIT;
