-- 푸시 알림 타입별 수신 설정. 점주가 푸시 타입을 끄고 켠다(행 없으면 기본 켜짐).
-- 발송 시 PushDispatcher가 user_id+type 으로 조회해 off면 스킵.
START TRANSACTION;

CREATE TABLE notification_preferences (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  type VARCHAR(40) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, type)
);
CREATE INDEX idx_notification_preferences_user ON notification_preferences(user_id);

CREATE TRIGGER update_notification_preferences_updated_at
  BEFORE UPDATE ON notification_preferences FOR EACH ROW EXECUTE FUNCTION update_updated_at();

COMMIT;
