-- 26-06-06-drop-insights-subscriptions.sql 롤백 — 6테이블을 빈 상태로 재생성.
-- 데이터는 복원되지 않는다(드롭 시 소실). 인스타그램 시드는 seed.sql 이전 버전 참조.

BEGIN;

CREATE TABLE trend_articles (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category TEXT NOT NULL CHECK (category IN ('flower', 'inspiration', 'business', 'industry')),
  title TEXT NOT NULL,
  summary TEXT NOT NULL,
  key_points JSONB NOT NULL DEFAULT '[]'::jsonb,
  source_url TEXT NOT NULL,
  source_name TEXT,
  published_at TIMESTAMPTZ,
  collected_at DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_trend_articles_category ON trend_articles(category);
CREATE INDEX idx_trend_articles_collected_at ON trend_articles(collected_at DESC);
CREATE UNIQUE INDEX idx_trend_articles_source_url ON trend_articles(source_url);

CREATE TABLE instagram_accounts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username TEXT NOT NULL UNIQUE,
  display_name TEXT,
  profile_url TEXT NOT NULL,
  region TEXT NOT NULL CHECK (region IN ('domestic', 'international')),
  sort_order INT DEFAULT 0,
  active BOOLEAN DEFAULT TRUE,
  memo TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_instagram_accounts_active ON instagram_accounts(active);
CREATE INDEX idx_instagram_accounts_region ON instagram_accounts(region);
CREATE TRIGGER update_instagram_accounts_updated_at
  BEFORE UPDATE ON instagram_accounts FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TABLE instagram_posts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  account_id BIGINT NOT NULL,
  shortcode TEXT NOT NULL UNIQUE,
  permalink TEXT NOT NULL,
  image_urls JSONB NOT NULL DEFAULT '[]'::jsonb,
  caption TEXT,
  like_count INT DEFAULT 0,
  posted_at TIMESTAMPTZ NOT NULL,
  scraped_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_instagram_posts_account_id ON instagram_posts(account_id);
CREATE INDEX idx_instagram_posts_posted_at ON instagram_posts(posted_at DESC);

CREATE TABLE insight_scraps (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  target_type TEXT NOT NULL CHECK (target_type IN ('trend', 'post')),
  target_id BIGINT NOT NULL,
  memo TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, target_type, target_id)
);
CREATE INDEX idx_insight_scraps_user ON insight_scraps(user_id);
CREATE INDEX idx_insight_scraps_target ON insight_scraps(target_type, target_id);
CREATE INDEX idx_insight_scraps_user_type_created
  ON insight_scraps(user_id, target_type, created_at DESC);
CREATE TRIGGER update_insight_scraps_updated_at
  BEFORE UPDATE ON insight_scraps FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TABLE subscriptions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL UNIQUE,
  store VARCHAR(16) NOT NULL CHECK (store IN ('apple', 'google')),
  product_id VARCHAR(128) NOT NULL,
  entitlement VARCHAR(64) NOT NULL DEFAULT 'premium',
  status VARCHAR(16) NOT NULL DEFAULT 'none' CHECK (status IN ('active', 'in_grace', 'expired', 'none')),
  original_transaction_id VARCHAR(128),
  current_period_end TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_subscriptions_status ON subscriptions(status);

CREATE TABLE subscription_events (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT,
  event_id VARCHAR(128),
  event_type VARCHAR(32) NOT NULL,
  store VARCHAR(16),
  product_id VARCHAR(128),
  raw_event JSONB,
  occurred_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_subscription_events_user_id ON subscription_events(user_id);

ALTER TABLE user_preferences
  ALTER COLUMN bottom_nav_items SET DEFAULT '["calendar","sales","expenses","customers","insights"]'::jsonb;

COMMIT;
