-- 커뮤니티 게시판(단일 커뮤니티) — 게시글/댓글/좋아요. soft delete + 비정규화 카운트.
-- FK 제약 미사용(간접참조) — 참조 무결성/연쇄정리는 애플리케이션 책임. all-tables-ddl.sql과 동일.
START TRANSACTION;

CREATE TABLE community_posts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  author_user_id BIGINT NOT NULL,
  category VARCHAR(20) NOT NULL CHECK (category IN ('notice', 'daily', 'question', 'knowledge', 'review', 'etc')),
  title VARCHAR(255) NOT NULL,
  content JSONB NOT NULL DEFAULT '{}'::jsonb,
  content_text TEXT NOT NULL DEFAULT '',
  image_urls TEXT[] NOT NULL DEFAULT '{}',
  is_secret BOOLEAN NOT NULL DEFAULT FALSE,
  is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
  like_count INTEGER NOT NULL DEFAULT 0,
  comment_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);

CREATE INDEX idx_community_posts_feed ON community_posts(is_pinned DESC, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_community_posts_category ON community_posts(category);
CREATE INDEX idx_community_posts_author ON community_posts(author_user_id);

CREATE TRIGGER update_community_posts_updated_at
  BEFORE UPDATE ON community_posts FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TABLE community_comments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  post_id BIGINT NOT NULL,
  parent_id BIGINT,
  author_user_id BIGINT NOT NULL,
  content TEXT NOT NULL,
  is_secret BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);

CREATE INDEX idx_community_comments_post ON community_comments(post_id);
CREATE INDEX idx_community_comments_parent ON community_comments(parent_id);

CREATE TABLE community_likes (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  post_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (post_id, user_id)
);

CREATE INDEX idx_community_likes_post ON community_likes(post_id);

COMMIT;
