-- 26-06-24-drop-trend-articles.sql 롤백 — trend_articles 재생성 + insight_scraps CHECK 복원.
-- trend_articles 데이터는 복원되지 않는다(드롭 시 소실됨). 스키마/제약만 되돌린다.
--
-- 순서:
--   1) trend_articles 테이블 + 인덱스 3종 재생성.
--   2) insight_scraps.target_type CHECK 를 ('grant') → ('trend','grant') 으로 복원.

START TRANSACTION;

-- 1) 트렌드·뉴스 기사 (공유 큐레이션) — 재생성.
CREATE TABLE trend_articles (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category TEXT NOT NULL CHECK (category IN ('flower', 'inspiration', 'business', 'industry')),
  title TEXT NOT NULL,
  summary TEXT NOT NULL,
  key_points JSONB NOT NULL DEFAULT '[]'::jsonb,
  source_url TEXT NOT NULL,
  source_name TEXT,
  published_at TIMESTAMPTZ,
  collected_at DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_trend_articles_category ON trend_articles(category);
CREATE INDEX idx_trend_articles_collected_at ON trend_articles(collected_at DESC);
CREATE UNIQUE INDEX idx_trend_articles_source_url ON trend_articles(source_url);

-- 2) target_type CHECK 복원: 'trend','grant' 모두 허용.
DO $$
DECLARE
  con_name TEXT;
BEGIN
  SELECT conname INTO con_name
  FROM pg_constraint
  WHERE conrelid = 'insight_scraps'::regclass
    AND contype = 'c'
    AND pg_get_constraintdef(oid) ILIKE '%target_type%';
  IF con_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE insight_scraps DROP CONSTRAINT %I', con_name);
  END IF;
END $$;

ALTER TABLE insight_scraps
  ADD CONSTRAINT insight_scraps_target_type_check CHECK (target_type IN ('trend', 'grant'));

COMMIT;
