-- flori 운영 콘솔 고도화 — 감사로그/발송이력/브로드캐스트/커뮤니티 모더레이션/공지배너/문의 인박스.
-- 슈퍼어드민(/admin/** @RequiresAdmin) 전용 운영 도구가 사용하는 테이블 모음.
-- 컨벤션: BIGINT IDENTITY PK, snake_case, FK 미사용(간접참조), soft-delete(deleted_at), updated_at 트리거.
-- 주의: 기존 notification_log(멱등성 dedup)와 다름 — 본 발송 이력은 notification_send_logs.
START TRANSACTION;

-- =============================================
-- 1) 운영자 감사 로그 (admin_audit_logs)
-- 모든 운영자 액션(인증 승인/거절, 유저 비활성, 콘텐츠 숨김/삭제, 발송, 설정변경, PII 열람)을 append-only로 기록.
-- 책임추적/컴플라이언스용. 삭제·수정 없음(append-only). before/after 는 metadata(jsonb).
-- =============================================
CREATE TABLE admin_audit_logs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  actor_user_id BIGINT NOT NULL,                 -- 액션 수행 운영자 users.id (간접참조)
  actor_email VARCHAR(255),                       -- 조회 편의용 비정규화 스냅샷
  action VARCHAR(60) NOT NULL,                    -- 예: VERIFICATION_APPROVE, USER_DEACTIVATE, POST_HIDE, BROADCAST_SEND ...
  target_type VARCHAR(40),                        -- 예: user, verification, post, comment, broadcast, announcement, inquiry, setting
  target_id VARCHAR(64),                          -- 대상 식별자(문자열 — 숫자 PK도 문자열로)
  summary TEXT,                                   -- 사람이 읽는 한 줄 요약
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,    -- {before, after, reason, ...}
  ip VARCHAR(45),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_admin_audit_logs_created ON admin_audit_logs(created_at DESC);
CREATE INDEX idx_admin_audit_logs_action ON admin_audit_logs(action, created_at DESC);
CREATE INDEX idx_admin_audit_logs_actor ON admin_audit_logs(actor_user_id, created_at DESC);

-- =============================================
-- 2) 알림 발송 이력 (notification_send_logs)
-- 모든 푸시 발송(예약 리마인더/공지/브로드캐스트 캠페인)을 발송 직후 기록한다.
-- PushDispatcher가 발송 결과(성공/실패/부분실패 카운트)와 함께 1행 기록 → 콘솔 발송 로그 화면에서 조회.
-- 기존 notification_log(멱등성)와 별개. broadcast_id 로 캠페인 발송을 묶는다.
-- =============================================
CREATE TABLE notification_send_logs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  source VARCHAR(20) NOT NULL DEFAULT 'web'       -- web(콘솔 수동) | cron(스케줄러) | system
    CHECK (source IN ('web', 'cron', 'system')),
  type VARCHAR(40) NOT NULL,                       -- broadcast | reservation_reminder | notice | ...
  segment VARCHAR(40),                             -- 브로드캐스트 세그먼트 키(있으면)
  target_user_id BIGINT,                           -- 단건 발송 대상(있으면)
  title VARCHAR(255),
  body TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'sent'       -- sent | failed | partial
    CHECK (status IN ('sent', 'failed', 'partial')),
  sent_count INTEGER NOT NULL DEFAULT 0,
  failed_count INTEGER NOT NULL DEFAULT 0,
  error_message TEXT,
  broadcast_id BIGINT,                             -- broadcasts.id (간접참조)
  actor_user_id BIGINT,                            -- web 발송 시 운영자(있으면)
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_notification_send_logs_created ON notification_send_logs(created_at DESC);
CREATE INDEX idx_notification_send_logs_type ON notification_send_logs(type, created_at DESC);
CREATE INDEX idx_notification_send_logs_status ON notification_send_logs(status, created_at DESC);
CREATE INDEX idx_notification_send_logs_broadcast ON notification_send_logs(broadcast_id);

-- =============================================
-- 3) 브로드캐스트 캠페인 (broadcasts)
-- 운영자가 세그먼트(전체/활성/인증완료/휴면/AI미사용 등)를 타깃해 푸시를 발송·예약한다.
-- 발송 시 세그먼트를 user_id 집합으로 해석 → PushDispatcher 반복 발송 → notification_send_logs 기록.
-- =============================================
CREATE TABLE broadcasts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  deep_link VARCHAR(500),                          -- 클릭 시 이동 경로(/admin/marketing 등)
  segment VARCHAR(40) NOT NULL DEFAULT 'all'       -- all | active_7d | verified | dormant_14d | ai_unused
    CHECK (segment IN ('all', 'active_7d', 'verified', 'dormant_14d', 'ai_unused')),
  status VARCHAR(20) NOT NULL DEFAULT 'draft'      -- draft | scheduled | sending | sent | failed
    CHECK (status IN ('draft', 'scheduled', 'sending', 'sent', 'failed')),
  scheduled_at TIMESTAMPTZ,                         -- 예약 발송 시각(있으면)
  sent_at TIMESTAMPTZ,
  target_count INTEGER NOT NULL DEFAULT 0,
  sent_count INTEGER NOT NULL DEFAULT 0,
  failed_count INTEGER NOT NULL DEFAULT 0,
  created_by BIGINT NOT NULL,                       -- 작성 운영자 users.id
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_broadcasts_status ON broadcasts(status, created_at DESC);
CREATE INDEX idx_broadcasts_scheduled ON broadcasts(scheduled_at) WHERE status = 'scheduled';
CREATE TRIGGER update_broadcasts_updated_at
  BEFORE UPDATE ON broadcasts FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 4) 커뮤니티 신고 (community_reports)
-- 사용자가 게시글/댓글을 신고하면 1행. 운영자가 신고 큐에서 처리(삭제/숨김/유지=dismiss).
-- 1인 1대상 1신고(unique). 신고 수는 (target_type,target_id)로 집계.
-- =============================================
CREATE TABLE community_reports (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  target_type VARCHAR(10) NOT NULL CHECK (target_type IN ('post', 'comment')),
  target_id BIGINT NOT NULL,                        -- community_posts.id 또는 community_comments.id
  reporter_user_id BIGINT NOT NULL,
  reason VARCHAR(20) NOT NULL                       -- spam | abuse | privacy | sexual | etc
    CHECK (reason IN ('spam', 'abuse', 'privacy', 'sexual', 'etc')),
  detail TEXT,                                       -- 신고 상세(선택)
  status VARCHAR(20) NOT NULL DEFAULT 'pending'      -- pending | resolved | dismissed
    CHECK (status IN ('pending', 'resolved', 'dismissed')),
  resolved_by BIGINT,                                -- 처리 운영자 users.id
  resolved_at TIMESTAMPTZ,
  resolution VARCHAR(20),                            -- deleted | hidden | dismissed
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
-- 1인 1대상 1신고.
CREATE UNIQUE INDEX uq_community_reports_one_per_user
  ON community_reports(target_type, target_id, reporter_user_id);
-- 신고 큐: 미처리 우선 최신순.
CREATE INDEX idx_community_reports_queue ON community_reports(status, created_at DESC);
CREATE INDEX idx_community_reports_target ON community_reports(target_type, target_id);

-- =============================================
-- 5) 커뮤니티 차단 (community_bans)
-- 운영자가 특정 유저의 커뮤니티 작성을 차단한다. expires_at NULL = 영구.
-- 차단 여부 = 해당 user_id 행 존재 AND (expires_at IS NULL OR expires_at > now).
-- =============================================
CREATE TABLE community_bans (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  reason TEXT,
  banned_by BIGINT NOT NULL,                         -- 처리 운영자 users.id
  expires_at TIMESTAMPTZ,                            -- NULL = 영구
  lifted_at TIMESTAMPTZ,                             -- 수동 해제 시각(있으면 차단 해제됨)
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
-- 활성 차단 1건만(해제 안 된 것). 부분 unique.
CREATE UNIQUE INDEX uq_community_bans_active
  ON community_bans(user_id) WHERE lifted_at IS NULL;
CREATE INDEX idx_community_bans_user ON community_bans(user_id);

-- 커뮤니티 게시글/댓글 숨김(가역) — 삭제(deleted_at, 비가역 tombstone)와 분리.
-- 숨김: 목록/상세에서 가리되 운영자가 되돌릴 수 있음. 신고 처리의 중간 단계.
ALTER TABLE community_posts ADD COLUMN hidden_at TIMESTAMPTZ;
ALTER TABLE community_posts ADD COLUMN hidden_by BIGINT;
ALTER TABLE community_comments ADD COLUMN hidden_at TIMESTAMPTZ;
ALTER TABLE community_comments ADD COLUMN hidden_by BIGINT;

-- =============================================
-- 6) 공지 배너 CMS (announcements)
-- 앱 내 모달/상단바 공지. 활성 토글 + 노출기간 + 클릭수 집계. soft-delete.
-- 사용자측은 활성·기간내 배너만 조회. onetime BannerController 패턴.
-- =============================================
CREATE TABLE announcements (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  placement VARCHAR(20) NOT NULL DEFAULT 'modal'    -- modal(전면) | bar(상단바)
    CHECK (placement IN ('modal', 'bar')),
  title VARCHAR(255) NOT NULL,
  body TEXT,
  image_url TEXT,                                    -- modal 이미지(선택)
  link_url VARCHAR(500),                             -- 클릭 시 이동(선택)
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  starts_at TIMESTAMPTZ,                             -- 노출 시작(NULL=즉시)
  ends_at TIMESTAMPTZ,                               -- 노출 종료(NULL=무기한)
  click_count INTEGER NOT NULL DEFAULT 0,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ
);
-- 사용자 노출 조회: 활성 + 미삭제.
CREATE INDEX idx_announcements_active
  ON announcements(placement, is_active) WHERE deleted_at IS NULL;
CREATE TRIGGER update_announcements_updated_at
  BEFORE UPDATE ON announcements FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 7) 1:1 문의 / 피드백 인박스 (support_inquiries)
-- 점주가 문의/피드백을 제출하면 1행. 운영자가 콘솔 인박스에서 답변/상태관리.
-- 답변은 1차로 단일 운영자 회신(answer) — 스레드형은 후속.
-- =============================================
CREATE TABLE support_inquiries (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,                           -- 제출 점주 users.id
  category VARCHAR(20) NOT NULL DEFAULT 'etc'        -- bug | feature | account | payment | feedback | etc
    CHECK (category IN ('bug', 'feature', 'account', 'payment', 'feedback', 'etc')),
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  image_urls TEXT[] NOT NULL DEFAULT '{}',
  status VARCHAR(20) NOT NULL DEFAULT 'open'         -- open | in_progress | resolved | closed
    CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
  answer TEXT,                                        -- 운영자 회신
  answered_by BIGINT,
  answered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_support_inquiries_queue ON support_inquiries(status, created_at DESC);
CREATE INDEX idx_support_inquiries_user ON support_inquiries(user_id, created_at DESC);
CREATE TRIGGER update_support_inquiries_updated_at
  BEFORE UPDATE ON support_inquiries FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 8) 탈퇴 사유 로그 (withdrawal_logs)
-- DELETE /me 시 수집하던 탈퇴 사유를 영속한다(기존엔 수집 후 폐기됨). 운영 대시보드 이탈 분석용.
-- 계정은 soft-delete 되므로 user_id는 탈퇴 시점 스냅샷(간접참조).
-- =============================================
CREATE TABLE withdrawal_logs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  reason VARCHAR(100),
  detail TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_withdrawal_logs_created ON withdrawal_logs(created_at DESC);

COMMIT;
