-- 백그라운드 작업(@Scheduled cron) 실행 로깅 — 콘솔 작업 로그 화면용.
-- job_run_status(작업당 1행 upsert) + job_run_logs(의미있는 실행만 append-only).
-- 컨벤션: BIGINT IDENTITY PK, snake_case, FK 미사용(간접참조).
START TRANSACTION;

CREATE TABLE job_run_status (
  job_name VARCHAR(60) PRIMARY KEY,
  last_status VARCHAR(20) NOT NULL
    CHECK (last_status IN ('success', 'failed', 'skipped')),
  last_run_at TIMESTAMPTZ NOT NULL,
  last_finished_at TIMESTAMPTZ,
  last_duration_ms INTEGER,
  last_processed_count INTEGER NOT NULL DEFAULT 0,
  last_error_message TEXT,
  last_success_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE job_run_logs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  job_name VARCHAR(60) NOT NULL,
  status VARCHAR(20) NOT NULL
    CHECK (status IN ('success', 'failed', 'skipped')),
  trigger VARCHAR(20) NOT NULL DEFAULT 'schedule'
    CHECK (trigger IN ('schedule', 'manual')),
  processed_count INTEGER NOT NULL DEFAULT 0,
  duration_ms INTEGER,
  error_message TEXT,
  actor_user_id BIGINT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  started_at TIMESTAMPTZ NOT NULL,
  finished_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_job_run_logs_created ON job_run_logs(created_at DESC);
CREATE INDEX idx_job_run_logs_job ON job_run_logs(job_name, created_at DESC);
CREATE INDEX idx_job_run_logs_status ON job_run_logs(status, created_at DESC);

COMMIT;
