-- flori AI 프롬프트 레지스트리 — 마케팅(블로그) 생성 프롬프트를 코드 상수에서 DB로 이관(SPEC-AI-008).
-- 슈퍼어드민 콘솔(/admin/prompts/** @RequiresAdmin)에서 CRUD·버전·활성화·플레이그라운드로 재배포 없이 튜닝.
-- DB엔 정적 부분(시스템·GEO규칙·출력스펙·모델·temp)만. 동적 데이터(키워드·말투샘플·매장맥락)는 게이트웨이가 코드 주입.
-- 컨벤션: BIGINT IDENTITY PK, snake_case, FK 미사용(간접참조), soft-delete(deleted_at), updated_at 트리거.
-- 폴백 불변식: 이 테이블이 비어도 ai-server geo_rules.py 기본값으로 블로그 생성이 동작한다.
START TRANSACTION;

-- 프롬프트 버전 — 채널당 active 1개. 본문 3조각 + 모델/파라미터 + 감사/소프트삭제.
CREATE TABLE ai_prompt (
  id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  channel        VARCHAR(20) NOT NULL DEFAULT 'blog' CHECK (channel IN ('blog')),
  version        VARCHAR(40) NOT NULL,              -- 'v1', 'v2-말투강화', '2026-06-21-실험'
  is_active      BOOLEAN NOT NULL DEFAULT FALSE,
  system_md      TEXT NOT NULL,                     -- 페르소나 + 말투 모방 지시
  rules_md       TEXT NOT NULL DEFAULT '',          -- GEO 구조 규칙
  output_spec_md TEXT NOT NULL DEFAULT '',          -- 출력 JSON 스펙
  model          VARCHAR(64),                       -- 비우면 ai-server 기본
  temperature    NUMERIC(3,2),
  max_tokens     INTEGER,
  notes          TEXT,                              -- 변경 사유
  created_by     VARCHAR(120),                      -- 어드민 식별
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at     TIMESTAMPTZ,
  UNIQUE (channel, version)
);
-- 채널당 active 1개만 강제(soft-delete 제외) — 활성화 트랜잭션의 동시성 안전망.
CREATE UNIQUE INDEX uq_ai_prompt_active_per_channel
  ON ai_prompt(channel) WHERE is_active = TRUE AND deleted_at IS NULL;
CREATE TRIGGER update_ai_prompt_updated_at
  BEFORE UPDATE ON ai_prompt FOR EACH ROW EXECUTE FUNCTION update_updated_at();

COMMIT;
