-- 26-06-06-unify-label-settings.sql 롤백.
-- label_settings를 다시 4테이블로 분리한다. color는 기본값으로 복원되고, 매출 채널(kind='channel')은 폐기된다.

BEGIN;

-- 1. 기존 4테이블 재생성
CREATE TABLE sale_categories (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  value VARCHAR(100) NOT NULL,
  label VARCHAR(100) NOT NULL,
  color VARCHAR(7) DEFAULT '#f43f5e',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (value, user_id)
);
CREATE INDEX idx_sale_categories_user_id ON sale_categories(user_id);

CREATE TABLE payment_methods (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  value VARCHAR(20) NOT NULL,
  label VARCHAR(100) NOT NULL,
  color VARCHAR(7) DEFAULT '#3b82f6',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (value, user_id)
);
CREATE INDEX idx_payment_methods_user_id ON payment_methods(user_id);

CREATE TABLE expense_categories (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  value VARCHAR(100) NOT NULL,
  label VARCHAR(100) NOT NULL,
  color VARCHAR(7) DEFAULT '#6b7280',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (value, user_id)
);
CREATE INDEX idx_expense_categories_user_id ON expense_categories(user_id);

CREATE TABLE expense_payment_methods (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  value VARCHAR(20) NOT NULL,
  label VARCHAR(100) NOT NULL,
  color VARCHAR(7) DEFAULT '#3b82f6',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (value, user_id)
);
CREATE INDEX idx_expense_payment_methods_user_id ON expense_payment_methods(user_id);

-- 2. 데이터 역이관 (channel은 복원 대상 없음 → 폐기)
INSERT INTO sale_categories (user_id, value, label, sort_order, created_at)
SELECT user_id, value, label, sort_order, created_at FROM label_settings WHERE domain = 'sale' AND kind = 'category';

INSERT INTO payment_methods (user_id, value, label, sort_order, created_at)
SELECT user_id, value, label, sort_order, created_at FROM label_settings WHERE domain = 'sale' AND kind = 'payment';

INSERT INTO expense_categories (user_id, value, label, sort_order, created_at)
SELECT user_id, value, label, sort_order, created_at FROM label_settings WHERE domain = 'expense' AND kind = 'category';

INSERT INTO expense_payment_methods (user_id, value, label, sort_order, created_at)
SELECT user_id, value, label, sort_order, created_at FROM label_settings WHERE domain = 'expense' AND kind = 'payment';

-- 3. 통합 테이블 제거
DROP TABLE label_settings;

COMMIT;
