-- 사전등록(waitlist) — 출시 전 선착순 100명 모집. 공개 폼(가게명+전화번호), 로그인 불필요.
-- 전화번호는 정규화(숫자만)하여 UNIQUE로 중복 등록 방지. 인증/테넌시와 무관한 독립 테이블.
START TRANSACTION;

CREATE TABLE waitlist_registrations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name   VARCHAR(50)  NOT NULL,
    phone       VARCHAR(20)  NOT NULL UNIQUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMIT;
