-- 경매 품목 스크랩(사장님별) — 경매 시세 탭에서 관심 품목(pum_name)을 북마크/필터.
-- A안: insight_scraps(target_id BIGINT)로는 품목명을 담을 수 없어 별도 테이블 신설.
-- 개인(user_id) 테이블 — 모든 쿼리 user_id 격리. FK 없음(간접참조).

START TRANSACTION;

CREATE TABLE flower_item_scraps (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  pum_name TEXT NOT NULL,                     -- 품목명(예: 장미, 국화)
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, pum_name)                  -- 같은 품목은 한 번만(멱등 토글)
);
CREATE INDEX idx_flower_item_scraps_user ON flower_item_scraps(user_id);

COMMIT;
