-- =============================================
-- Flori Server — Flyway baseline (BIGINT IDENTITY 통합 스키마)
-- 설계 원칙:
--   * 기본키(PK)는 BIGINT GENERATED BY DEFAULT AS IDENTITY — DB가 시퀀스로 생성한다.
--     (UUID 전략에서 전환: 인덱스 크기·조인 비용 절감, FK는 BIGINT로 정렬)
--   * Supabase RLS(행 수준 보안) 정책 전부 제거 → 멀티테넌시는 애플리케이션이 강제
--   * Supabase 인증 테이블 FK 제거 → 자체 users 테이블 추가, 모든 user_id가 users(id) 참조
--   * jsonb / 배열 / timestamptz 타입은 그대로 유지
--   * 복합 unique 제약 유지: (phone,user_id), (value,user_id), (name,user_id) 등
-- 통합 범위:
--   * 과거 V1~V7 마이그레이션의 최종 상태를 단일 baseline으로 합침
--   * V6 OAuth provider 컬럼 + 부분 unique 인덱스, V3 refresh_tokens,
--     V4 subscriptions/subscription_events, V5 notification_log 포함
--   * V7 정리 반영: 입금대조/카드수수료 컬럼·card_company_settings·app_config·
--     sales.reservation_id/photos·customers 구매통계 컬럼은 재도입하지 않음
-- =============================================

-- updated_at 자동 갱신 트리거 함수
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =============================================
-- 사용자 (자체 인증) — 원본 Supabase 인증 테이블 대체
-- 소셜 전용 사용자는 email/password_hash가 NULL일 수 있다(V6 반영).
-- =============================================
CREATE TABLE users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  email VARCHAR(255) UNIQUE,
  password_hash VARCHAR(255),
  name VARCHAR(100),
  provider VARCHAR(20) NOT NULL DEFAULT 'LOCAL',
  provider_id VARCHAR(255),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 같은 소셜 신원 = 같은 사용자 (provider_id 있는 행에만 적용)
CREATE UNIQUE INDEX uq_users_provider_identity
  ON users (provider, provider_id)
  WHERE provider_id IS NOT NULL;

CREATE TRIGGER update_users_updated_at
  BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- refresh token 저장소 (회전/무효화 추적)
-- 보안: 원문 대신 SHA-256 해시만 저장. 회전 시 이전 토큰 revoke, 로그아웃 시 revoke.
-- =============================================
CREATE TABLE refresh_tokens (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash VARCHAR(64) NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens(expires_at);

-- =============================================
-- 고객
-- 구매 통계(횟수/총액/최초·최근 구매일)는 sales에서 실시간 집계(SSOT) — 컬럼 미보유(V7).
-- =============================================
CREATE TABLE customers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  grade VARCHAR(20) DEFAULT 'new' CHECK (grade IN ('new', 'regular', 'vip', 'blacklist')),
  gender VARCHAR(10) DEFAULT NULL CHECK (gender IN ('male', 'female')),
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (phone, user_id)
);

CREATE INDEX idx_customers_phone ON customers(phone);
CREATE INDEX idx_customers_grade ON customers(grade);
CREATE INDEX idx_customers_user_id ON customers(user_id);

CREATE TRIGGER update_customers_updated_at
  BEFORE UPDATE ON customers FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 고정비(반복 지출) 템플릿 — expenses.recurring_id가 참조하므로 먼저 생성
-- =============================================
CREATE TABLE recurring_expenses (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  item_name TEXT NOT NULL,
  category VARCHAR(30) NOT NULL,
  unit_price INTEGER NOT NULL CHECK (unit_price >= 0),
  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
  payment_method VARCHAR(20) NOT NULL,
  vendor TEXT,
  note TEXT,
  frequency VARCHAR(10) NOT NULL CHECK (frequency IN ('weekly', 'monthly', 'yearly')),
  interval_count INTEGER NOT NULL DEFAULT 1 CHECK (interval_count > 0),
  days_of_week INTEGER[] NOT NULL DEFAULT '{}',   -- weekly: 0(일)~6(토)
  days_of_month INTEGER[] NOT NULL DEFAULT '{}',  -- monthly: 1~31
  yearly_dates JSONB NOT NULL DEFAULT '[]'::jsonb, -- yearly: [{"m":n,"d":n}]
  start_date DATE NOT NULL,
  end_date DATE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_recurring_expenses_user ON recurring_expenses(user_id);
CREATE INDEX idx_recurring_expenses_active ON recurring_expenses(is_active) WHERE is_active = TRUE;

CREATE TRIGGER update_recurring_expenses_updated_at
  BEFORE UPDATE ON recurring_expenses FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 예약 (sale_id FK는 sales 생성 후 ALTER로 추가 — 순환 참조 해소)
-- =============================================
CREATE TABLE reservations (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  time TIME,
  customer_name TEXT NOT NULL DEFAULT '',
  customer_phone TEXT,
  title TEXT NOT NULL DEFAULT '',
  description TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'completed', 'cancelled')),
  sale_id BIGINT,
  amount INTEGER DEFAULT 0,
  reminder_at TIMESTAMPTZ,
  reminder_sent BOOLEAN NOT NULL DEFAULT FALSE,
  pickup_completed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_reservations_date ON reservations(date);
CREATE INDEX idx_reservations_status ON reservations(status);
CREATE INDEX idx_reservations_user_id ON reservations(user_id);

CREATE TRIGGER update_reservations_updated_at
  BEFORE UPDATE ON reservations FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 매출 (입금대조/카드수수료 컬럼은 V7에서 제거 — 재도입하지 않음)
-- =============================================
CREATE TABLE sales (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  product_name VARCHAR(200) NOT NULL,
  product_category VARCHAR(100),
  amount INTEGER NOT NULL,
  payment_method VARCHAR(20) NOT NULL
    CHECK (payment_method IN ('cash', 'card', 'transfer', 'naverpay', 'kakaopay', 'unpaid')),
  reservation_channel VARCHAR(20) DEFAULT 'other'
    CHECK (reservation_channel IN ('phone', 'kakaotalk', 'naver_booking', 'road', 'other')),
  customer_name VARCHAR(100),
  customer_phone VARCHAR(20),
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  note TEXT,
  is_unpaid BOOLEAN NOT NULL DEFAULT FALSE,
  has_review BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 예약 <-> 매출 양방향 FK
ALTER TABLE reservations ADD CONSTRAINT reservations_sale_id_fkey
  FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE SET NULL;

CREATE INDEX idx_sales_date ON sales(date);
CREATE INDEX idx_sales_customer_id ON sales(customer_id);
CREATE INDEX idx_sales_payment_method ON sales(payment_method);
CREATE INDEX idx_sales_user_id ON sales(user_id);

CREATE TRIGGER update_sales_updated_at
  BEFORE UPDATE ON sales FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 지출 (category CHECK는 원본에서 제거됨 — 커스텀 카테고리 허용)
-- =============================================
CREATE TABLE expenses (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  item_name VARCHAR(200) NOT NULL,
  category VARCHAR(30) NOT NULL,
  unit_price INTEGER NOT NULL,
  quantity INTEGER DEFAULT 1,
  total_amount INTEGER NOT NULL,
  payment_method VARCHAR(20) NOT NULL
    CHECK (payment_method IN ('cash', 'card', 'transfer', 'naverpay', 'kakaopay')),
  card_company VARCHAR(50),
  vendor VARCHAR(100),
  note TEXT,
  recurring_id BIGINT REFERENCES recurring_expenses(id) ON DELETE SET NULL,
  is_recurring_modified BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  -- 같은 템플릿·같은 날짜 중복 자동생성 방지(NULL recurring_id는 distinct 취급)
  CONSTRAINT expenses_recurring_date_unique UNIQUE (recurring_id, date)
);

CREATE INDEX idx_expenses_date ON expenses(date);
CREATE INDEX idx_expenses_category ON expenses(category);
CREATE INDEX idx_expenses_user_id ON expenses(user_id);

CREATE TRIGGER update_expenses_updated_at
  BEFORE UPDATE ON expenses FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 고정비 skip ("이것만 삭제" 시 자동생성 재발 방지)
-- =============================================
CREATE TABLE recurring_skips (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  recurring_id BIGINT NOT NULL REFERENCES recurring_expenses(id) ON DELETE CASCADE,
  skip_date DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (recurring_id, skip_date)
);

CREATE INDEX idx_recurring_skips_user ON recurring_skips(user_id);

-- =============================================
-- 매출 카테고리 (value=영문 저장값, label=한글 표시값)
-- =============================================
CREATE TABLE sale_categories (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  value VARCHAR(100) NOT NULL,
  label VARCHAR(100) NOT NULL,
  color VARCHAR(7) DEFAULT '#f43f5e',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (value, user_id)
);

CREATE INDEX idx_sale_categories_user_id ON sale_categories(user_id);

-- =============================================
-- 매출 결제방식
-- =============================================
CREATE TABLE payment_methods (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  value VARCHAR(20) NOT NULL,
  label VARCHAR(100) NOT NULL,
  color VARCHAR(7) DEFAULT '#3b82f6',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (value, user_id)
);

CREATE INDEX idx_payment_methods_user_id ON payment_methods(user_id);

-- =============================================
-- 지출 카테고리
-- =============================================
CREATE TABLE expense_categories (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  value VARCHAR(100) NOT NULL,
  label VARCHAR(100) NOT NULL,
  color VARCHAR(7) DEFAULT '#6b7280',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (value, user_id)
);

CREATE INDEX idx_expense_categories_user_id ON expense_categories(user_id);

-- =============================================
-- 지출 결제방식
-- =============================================
CREATE TABLE expense_payment_methods (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  value VARCHAR(20) NOT NULL,
  label VARCHAR(100) NOT NULL,
  color VARCHAR(7) DEFAULT '#3b82f6',
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (value, user_id)
);

CREATE INDEX idx_expense_payment_methods_user_id ON expense_payment_methods(user_id);

-- =============================================
-- 사진 태그
-- =============================================
CREATE TABLE photo_tags (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(50) NOT NULL,
  color VARCHAR(7) DEFAULT '#6b7280',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (name, user_id)
);

CREATE INDEX idx_photo_tags_user_id ON photo_tags(user_id);

-- =============================================
-- 사진 카드 (photos: [{url, originalName}] jsonb)
-- =============================================
CREATE TABLE photo_cards (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  tags TEXT[] DEFAULT '{}',
  photos JSONB DEFAULT '[]',
  sale_id BIGINT REFERENCES sales(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_photo_cards_tags ON photo_cards USING GIN(tags);
CREATE INDEX idx_photo_cards_sale_id ON photo_cards(sale_id);
CREATE INDEX idx_photo_cards_created_at ON photo_cards(created_at DESC);
CREATE INDEX idx_photo_cards_user_id ON photo_cards(user_id);

CREATE TRIGGER update_photo_cards_updated_at
  BEFORE UPDATE ON photo_cards FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 푸시 구독 (원본 Web Push 컬럼 유지 — FCM 토큰도 endpoint에 저장)
-- =============================================
CREATE TABLE push_subscriptions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  endpoint TEXT NOT NULL UNIQUE,
  p256dh TEXT,
  auth TEXT,
  user_agent TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_push_subscriptions_user_id ON push_subscriptions(user_id);

CREATE TRIGGER update_push_subscriptions_updated_at
  BEFORE UPDATE ON push_subscriptions FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 캘린더 이벤트 (다중일 일정)
-- =============================================
CREATE TABLE calendar_events (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  color VARCHAR(7) NOT NULL DEFAULT '#f43f5e',
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_calendar_events_user_id ON calendar_events(user_id);
CREATE INDEX idx_calendar_events_range ON calendar_events(start_date, end_date);

CREATE TRIGGER update_calendar_events_updated_at
  BEFORE UPDATE ON calendar_events FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 인사이트: 트렌드 기사 (공유 읽기 — 테넌트 무관)
-- =============================================
CREATE TABLE trend_articles (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category TEXT NOT NULL CHECK (category IN ('flower', 'inspiration', 'business', 'industry')),
  title TEXT NOT NULL,
  summary TEXT NOT NULL,
  key_points JSONB NOT NULL DEFAULT '[]'::jsonb,
  source_url TEXT NOT NULL,
  source_name TEXT,
  published_at TIMESTAMPTZ,
  collected_at DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_trend_articles_category ON trend_articles(category);
CREATE INDEX idx_trend_articles_collected_at ON trend_articles(collected_at DESC);
CREATE UNIQUE INDEX idx_trend_articles_source_url ON trend_articles(source_url);

-- =============================================
-- 인사이트: 인스타그램 계정 (공유)
-- =============================================
CREATE TABLE instagram_accounts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username TEXT NOT NULL UNIQUE,
  display_name TEXT,
  profile_url TEXT NOT NULL,
  region TEXT NOT NULL CHECK (region IN ('domestic', 'international')),
  sort_order INT DEFAULT 0,
  active BOOLEAN DEFAULT TRUE,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_instagram_accounts_active ON instagram_accounts(active);
CREATE INDEX idx_instagram_accounts_region ON instagram_accounts(region);

CREATE TRIGGER update_instagram_accounts_updated_at
  BEFORE UPDATE ON instagram_accounts FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 인사이트: 인스타그램 포스트 (공유)
-- =============================================
CREATE TABLE instagram_posts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  account_id BIGINT NOT NULL REFERENCES instagram_accounts(id) ON DELETE CASCADE,
  shortcode TEXT NOT NULL UNIQUE,
  permalink TEXT NOT NULL,
  image_urls JSONB NOT NULL DEFAULT '[]'::jsonb,
  caption TEXT,
  like_count INT DEFAULT 0,
  posted_at TIMESTAMPTZ NOT NULL,
  scraped_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_instagram_posts_account_id ON instagram_posts(account_id);
CREATE INDEX idx_instagram_posts_posted_at ON instagram_posts(posted_at DESC);

-- =============================================
-- 유저 설정 (하단바 커스터마이즈) — PK이자 FK인 user_id
-- =============================================
CREATE TABLE user_preferences (
  user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  bottom_nav_items JSONB NOT NULL DEFAULT '["calendar","sales","expenses","customers","insights"]'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER update_user_preferences_updated_at
  BEFORE UPDATE ON user_preferences FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 인사이트 스크랩/메모 (polymorphic: target_type + target_id)
-- target_id는 trend_articles.id 또는 instagram_posts.id를 가리키는 BIGINT 참조.
-- =============================================
CREATE TABLE insight_scraps (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  target_type TEXT NOT NULL CHECK (target_type IN ('trend', 'post')),
  target_id BIGINT NOT NULL,
  memo TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, target_type, target_id)
);

CREATE INDEX idx_insight_scraps_user ON insight_scraps(user_id);
CREATE INDEX idx_insight_scraps_target ON insight_scraps(target_type, target_id);
CREATE INDEX idx_insight_scraps_user_type_created
  ON insight_scraps(user_id, target_type, created_at DESC);

CREATE TRIGGER update_insight_scraps_updated_at
  BEFORE UPDATE ON insight_scraps FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 구독/결제 (SPEC-SERVER-014): 앱스토어 IAP + RevenueCat 웹훅으로 갱신되는 사용자별 구독 상태.
-- 서버가 SSOT — 앱은 GET /subscription 으로 상태를 동기화한다.
-- =============================================
CREATE TABLE subscriptions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  store VARCHAR(16) NOT NULL CHECK (store IN ('apple', 'google')),
  product_id VARCHAR(128) NOT NULL,
  entitlement VARCHAR(64) NOT NULL DEFAULT 'premium',
  status VARCHAR(16) NOT NULL DEFAULT 'none' CHECK (status IN ('active', 'in_grace', 'expired', 'none')),
  original_transaction_id VARCHAR(128),
  current_period_end TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_subscriptions_status ON subscriptions(status);

-- 웹훅 이벤트 이력(감사/디버깅용 append-only 로그). raw_event 는 원본 페이로드.
CREATE TABLE subscription_events (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  event_id VARCHAR(128),
  event_type VARCHAR(32) NOT NULL,
  store VARCHAR(16),
  product_id VARCHAR(128),
  raw_event JSONB,
  occurred_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_subscription_events_user_id ON subscription_events(user_id);

-- =============================================
-- 알림 발송 멱등성 로그.
-- 같은 (user_id, notification_type, dedup_key) 알림을 중복 발송하지 않도록 원자적으로 기록한다.
-- 스케줄러 재기동·중복 트리거 시 INSERT ... ON CONFLICT DO NOTHING 으로 1회 발송 보장(at-most-once).
-- =============================================
CREATE TABLE notification_log (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  notification_type VARCHAR(40) NOT NULL,
  dedup_key VARCHAR(64) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, notification_type, dedup_key)
);
